### ISSUE TITLE
Not possible to read negative position values.

### ISSUE THREAD

**Issue by bastiMachine** [woven-planet/go-zserio#103]
Hello everyone,

it is not possible to read 2d positions with negative lat/lon values. Negative values get casted into uint32.

I think that the line where this problem occurs is the following:

https://github.com/woven-planet/go-zserio/blob/7664ccd24617ad1cdd0e05747260af9a2f7deea5/ztype/delta_context.go#L103

Thanks for solving.

**Comment by Danaozhong** [comment]
@bastiMachine Thank you very much for the problem report. I was able to reproduce the problem you reported in this PR: https://github.com/woven-planet/go-zserio/pull/104
I am working on a fix.

**Comment by Danaozhong** [comment]
This PR should fix the issue reported here: https://github.com/woven-planet/go-zserio/pull/104.
