### ISSUE TITLE
ztype.ExternType does not satisfy zserio.PackableZserioType (missing method Clone)

### ISSUE THREAD

**Issue by jo-me** [woven-planet/go-zserio#116]
Generating code with the lastes version from main branch yields several compile errors in the Go code.
One of them is in the _instructions_ package's JunctionViewImageList type. 

Example line:
`ImageDataArrayProperties.ArrayTraits = ztype.ObjectArrayTraits[*ztype.ExternType]{}`

Compile rrror:
*ztype.ExternType does not satisfy zserio.PackableZserioType (missing method Clone)

Jochen Mehlhorn <jochen.mehlhorn@mercedes-benz.com>, Mercedes-Benz Tech Innovation GmbH

[Provider Information](https://github.com/Daimler/daimler-foss/blob/master/PROVIDER_INFORMATION.md)

**Comment by Danaozhong** [comment]
Thank you for this problem report!

When debugging this issue,I realized our `zserio` implementation did not support array types of `extern`/`bytes` types. I added them with https://github.com/woven-planet/go-zserio/pull/117 .

May I ask which package you are using? We are not using any zserio packages that use arrays of extern or bytes types, so we didn't notice this issue earier. It would help us to make debugging a bit easier.

**Comment by Danaozhong** [comment]
The problem should be fixed with https://github.com/woven-planet/go-zserio/pull/117. 

I generated the `JunctionViewImageList` type, and the array traits now should look like:
`ImageDataArrayProperties.ArrayTraits = ztype.BitBufferArrayTraits{}`.
I could compile it with no errors now.

**Comment by jo-me** [comment]
I can confirm that these errors are gone with the latest version.
Thanks for your efforts!

Jochen Mehlhorn <jochen.mehlhorn@mercedes-benz.com>, Mercedes-Benz Tech Innovation GmbH

[Provider Information](https://github.com/Daimler/daimler-foss/blob/master/PROVIDER_INFORMATION.md)
