### ISSUE TITLE
Bazel Windows Issues

### ISSUE THREAD

**Issue by Danaozhong** [woven-planet/go-zserio#128]
Currently, several Bazel commands in this repository don't work on Windows:

- I couldn't get `buildifier` to run under Windows. It fails with:
```
FATAL: ExecuteProgram(C:\users\...\...(...\execroot\__main__\bazel-out\x64_windows-fastbuild\bin\buildifier.bash) failed:
ERROR: src/main/native/windows/process.cc(202): CreateProcessW("C:\users\...\...(...\execroot\__main__\bazel-out\x64_windows-fastbuild\bin\buildifier.bash"): %1 is not a valid Win32 application.
```
root cause seems to be https://github.com/bazelbuild/buildtools/issues/346 .
- [internal/parser/BUILD.bazel](https://github.com/woven-planet/go-zserio/blob/main/internal/parser/BUILD.bazel) uses `sh_binary`, which is not supported on Windows.

**Comment by aignas** [comment]
I think #136 should fix this as I have switched to using pre-built binaries of `buildifier`.
