### ISSUE TITLE
Unmarshalling zserio from file

### ISSUE THREAD

**Issue by jo-me** [woven-planet/go-zserio#145]
Hi,
I'm investigating a more memory-friendly way of unmarshalling lots of zserio-encoded NDS.Live tiles.

Up until now, I used a []byte containing the zserio data and unmarshalled like this:

```
reader := zstream.NewReader(bytes.NewReader(zserioBytes))
var zsrTile tile_api.SmartLayerTile
zsrTile.UnmarshalZserio(reader); 
```

In order to prevent having to have all the input data in memory (especially during concurrent processing), I wanted to try what happens if i stream the data directly from a file reader:

```
f, _ := os.Open(fileName)
fileReader := bufio.NewReader(f)
bitReader := zstream.NewReader(fileReader)
zsrTile.UnmarshalZserio(reader); 
```

However, this earns me a `read number of bytes didn't match` error on the same data (error occurring in the tile layers' ExternData part).

I suspect that the io.File may not support some operation that the bufio.Reader uses in this case. 
Intuitively, I'd say that zserio data should be decodeable sequentially in a single sweep, but I have not digged into that.

Should it be possible to decode directly from a file? 
Do you maybe have an example?

Thanks!

Jochen Mehlhorn <jochen.mehlhorn@mercedes-benz.com>, Mercedes-Benz Tech Innovation GmbH

[Provider Information](https://github.com/Daimler/daimler-foss/blob/master/PROVIDER_INFORMATION.md)

**Comment by jo-me** [comment]
The issue indeed occurs when reading the "large" data layer. The bytes returned do not match the expected size.
Reason is that the bufio.Reader does not load the next chunks of the file but surrenders with the currently available data in the buffer (max 4096 bytes) because read and write positions are _misaligned_. 

![image](https://github.com/user-attachments/assets/1a3b02e4-d2dc-4fb4-8528-74fe52447f19)

**Comment by wichert** [comment]
Being able to decode from a stream is certainly a desirable goal. I'm not sure why this happens - it does sound like a bug.

**Comment by wichert** [comment]
@jo-me is there a minimum data size where this happens? Or does it always break if you try reading from a stream?

**Comment by wichert** [comment]
I can reproduce this with one of our level 14 map tiles. My code to reproduce this is:

```go
package main

import (
	"bufio"
	"fmt"
	"os"

	"internal.git.service/ndslive/smart/v2022_03/tile"
	"github.com/woven-planet/go-zserio/zstream"
)

func main() {
	f, err := os.Open("smart.bin")
	if err != nil {
		fmt.Printf("can not open smart.bin: %e\n", err)
		os.Exit(1)
	}
	fileReader := bufio.NewReader(f)
	bitReader := zstream.NewReader(fileReader)
	var zsrTile tile.SmartLayerTile
	if err := zsrTile.UnmarshalZserio(bitReader); err != nil {
		fmt.Printf("failed to unmarshall: %e\n", err)
		os.Exit(1)
	}
}
```

**Comment by wichert** [comment]
The problem  here is pretty obvious: `ztype.ReadExtern` does not deal with short reads. These happen due to how `bufio.Reader` is implemented: it will read until the end of its butter, and only refill the buffer on the next call. The solution here should be to use `io.ReadFull`.

**Comment by wichert** [comment]
@jo-me can you check if #148 fixes the problem for you?

**Comment by jo-me** [comment]
@wichert I can confirm that this works with the latest version!
Thanks a lot!
