### ISSUE TITLE
go-zserio generates files with long names

### ISSUE THREAD

**Issue by bilinli** [woven-planet/go-zserio#95]
I tried to use go-zserio to compile the NDS.live schema and got the generated files with such long names that windows system doesn't even support.  

![image](https://user-images.githubusercontent.com/65456669/187621259-643f8bb5-9284-44a1-b264-71ddb98d0a65.png)

It would be very helpful to shorten the name of source file.

**Comment by wichert** [comment]
Interestingly we have not run into this problem, even though some of our developers do use Windows. @Danaozhong do you have any idea why you are not impacted by this?

**Comment by Danaozhong** [comment]
Hello @bilinli , very sorry for my late reply, I was on sick leave. I tried generating the files on my side, and was successful in generating and compiling the files on Windows 10. I assume the reason it works on my side is that I have enabled support for Windows Long Path. The file names are indeed very long - the reason for that is that these types are generated out of many template instantiations, and each template parameter type is added to the file name.

For the time being, would enabling Windows Long Path be a workaround for you?

**Comment by bilinli** [comment]
Thank you for your reply. I checked the problem again and found out that the problem is not with Windows system, but with VSCode. The files with long names can be opened with other editors. Can you open these in VSCode? Or do you use other IDE?

**Comment by Danaozhong** [comment]
@bilinli I had a look today, and was able to open all the files in `traffic/instantiations` in Visual Studio Code (on Windows 10). May I ask what kind of error you see?
